
export const weatherResponseMock = {
  "queryCost": 1,
  "latitude": -37.8174,
  "longitude": 144.968,
  "resolvedAddress": "Melbourne, VIC 3000, Australia",
  "address": "Melbourne",
  "timezone": "Australia/Melbourne",
  "tzoffset": 11,
  "description": "Similar temperatures continuing with a chance of rain multiple days.",
  "days": [
    {
      "datetime": "2023-12-06",
      "datetimeEpoch": 1701781200,
      "tempmax": 22.7,
      "tempmin": 12,
      "temp": 17.3,
      "feelslikemax": 22.7,
      "feelslikemin": 12,
      "feelslike": 17.3,
      "dew": 10.6,
      "humidity": 66.5,
      "precip": 0,
      "precipprob": 0,
      "precipcover": 0,
      "preciptype": null,
      "snow": 0,
      "snowdepth": 0,
      "windgust": 17.3,
      "windspeed": 24.1,
      "winddir": 187.1,
      "pressure": 1018.2,
      "cloudcover": 78.8,
      "visibility": 12.4,
      "solarradiation": 5.1,
      "solarenergy": 0.4,
      "uvindex": 1,
      "severerisk": 10,
      "sunrise": "05:51:27",
      "sunriseEpoch": 1701802287,
      "sunset": "20:30:42",
      "sunsetEpoch": 1701855042,
      "moonphase": 0.78,
      "conditions": "Partially cloudy",
      "description": "Partly cloudy throughout the day.",
      "icon": "partly-cloudy-day",
      "stations": [
        "YMAV",
        "D6954",
        "YMML"
      ],
      "source": "comb",
      "hours": [
        {
          "datetime": "12:00:00",
          "datetimeEpoch": 1701824400,
          "temp": 20,
          "feelslike": 20,
          "humidity": 56.15,
          "dew": 11,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 8.6,
          "windspeed": 13,
          "winddir": 170,
          "pressure": 1019,
          "visibility": 10,
          "cloudcover": 25,
          "solarradiation": 0,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": [
            "D6954",
            "YMML"
          ],
          "source": "obs"
        },
        {
          "datetime": "13:00:00",
          "datetimeEpoch": 1701828000,
          "temp": 20.8,
          "feelslike": 20.8,
          "humidity": 50.27,
          "dew": 10.1,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 10.1,
          "windspeed": 15.8,
          "winddir": 179,
          "pressure": 1018.9,
          "visibility": 10,
          "cloudcover": 25,
          "solarradiation": 0,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": [
            "YMAV",
            "D6954",
            "YMML"
          ],
          "source": "obs"
        }
      ]
    },
    {
      "datetime": "2023-12-06",
      "datetimeEpoch": 1701781200,
      "tempmax": 22.7,
      "tempmin": 12,
      "temp": 17.3,
      "feelslikemax": 22.7,
      "feelslikemin": 12,
      "feelslike": 17.3,
      "dew": 10.6,
      "humidity": 66.5,
      "precip": 0,
      "precipprob": 0,
      "precipcover": 0,
      "preciptype": null,
      "snow": 0,
      "snowdepth": 0,
      "windgust": 17.3,
      "windspeed": 24.1,
      "winddir": 187.1,
      "pressure": 1018.2,
      "cloudcover": 78.8,
      "visibility": 12.4,
      "solarradiation": 5.1,
      "solarenergy": 0.4,
      "uvindex": 1,
      "severerisk": 10,
      "sunrise": "05:51:27",
      "sunriseEpoch": 1701802287,
      "sunset": "20:30:42",
      "sunsetEpoch": 1701855042,
      "moonphase": 0.78,
      "conditions": "Partially cloudy",
      "description": "Partly cloudy throughout the day.",
      "icon": "partly-cloudy-day",
      "stations": [
        "YMAV",
        "D6954",
        "YMML"
      ],
      "source": "comb",
      "hours": [
        {
          "datetime": "12:00:00",
          "datetimeEpoch": 1701824400,
          "temp": 20,
          "feelslike": 20,
          "humidity": 56.15,
          "dew": 11,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 8.6,
          "windspeed": 13,
          "winddir": 170,
          "pressure": 1019,
          "visibility": 10,
          "cloudcover": 25,
          "solarradiation": 0,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": [
            "D6954",
            "YMML"
          ],
          "source": "obs"
        },
        {
          "datetime": "13:00:00",
          "datetimeEpoch": 1701828000,
          "temp": 20.8,
          "feelslike": 20.8,
          "humidity": 50.27,
          "dew": 10.1,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 10.1,
          "windspeed": 15.8,
          "winddir": 179,
          "pressure": 1018.9,
          "visibility": 10,
          "cloudcover": 25,
          "solarradiation": 0,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": [
            "YMAV",
            "D6954",
            "YMML"
          ],
          "source": "obs"
        }
      ]
    }
  ],
  "alerts": [],
  "stations": {
    "YMAV": {
      "distance": 49724,
      "latitude": -38.03,
      "longitude": 144.47,
      "useCount": 0,
      "id": "YMAV",
      "name": "YMAV",
      "quality": 50,
      "contribution": 0
    },
    "D6954": {
      "distance": 12920,
      "latitude": -37.905,
      "longitude": 145.064,
      "useCount": 0,
      "id": "D6954",
      "name": "DW6954 Melbourne AU",
      "quality": 0,
      "contribution": 0
    },
    "YMML": {
      "distance": 19905,
      "latitude": -37.67,
      "longitude": 144.84,
      "useCount": 0,
      "id": "YMML",
      "name": "YMML",
      "quality": 50,
      "contribution": 0
    },
    "D7251": {
      "distance": 13260,
      "latitude": -37.935,
      "longitude": 144.992,
      "useCount": 0,
      "id": "D7251",
      "name": "DW7251 Hampton AU",
      "quality": 0,
      "contribution": 0
    },
    "E5657": {
      "distance": 3436,
      "latitude": -37.8,
      "longitude": 145,
      "useCount": 0,
      "id": "E5657",
      "name": "EW5657 Elwood AU",
      "quality": 0,
      "contribution": 0
    }
  },
  "currentConditions": {
    "datetime": "19:45:00",
    "datetimeEpoch": 1701852300,
    "temp": 19.4,
    "feelslike": 19.4,
    "humidity": 62.5,
    "dew": 12.1,
    "precip": 0,
    "precipprob": 0,
    "snow": 0,
    "snowdepth": 0,
    "preciptype": null,
    "windgust": 17.1,
    "windspeed": 6.4,
    "winddir": 178,
    "pressure": 1017,
    "visibility": 10,
    "cloudcover": 95.7,
    "solarradiation": 115,
    "solarenergy": 0.4,
    "uvindex": 1,
    "conditions": "Overcast",
    "icon": "cloudy",
    "stations": [
      "D6954",
      "D7251",
      "YMML",
      "E5657"
    ],
    "source": "obs",
    "sunrise": "05:51:27",
    "sunriseEpoch": 1701802287,
    "sunset": "20:30:42",
    "sunsetEpoch": 1701855042,
    "moonphase": 0.78
  }
}
